version: "3.8"

services:
  six-city-renovation-frontend:
    container_name: six-city-renovation-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:${PORT}"
    environment:
       - NODE_ENV=production
    restart: always

# docker compose -f docker-compose.dev.yml up --build
